import { DocSection } from './docs.models';

export const DOCS: DocSection[] = [
  {
    id: 'what-is-teamwhistle',
    title: 'docs.whatisteamwhistle.title',
    blocks: [
      { type: 'text', content: 'docs.whatisteamwhistle.text1' },
      { type: 'image', src: 'assets/favicon.ico' },
    ]
  },
  {
    id: 'getting-started',
    title: 'docs.gettingstarted.title',
    blocks: [
      { type: 'text', content: 'docs.gettingstarted.text1' },
      { type: 'tip', content: 'docs.gettingstarted.tip1' },
      { type: 'text', content: 'docs.gettingstarted.text2' },
      { type: 'image', src: 'assets/docs/startingguide.png'},
      { type: 'tip', content: 'docs.gettingstarted.tip2' },
    ]
  },
  {
    id: 'matches',
    title: 'docs.matches.title',
    blocks: [
      { type: 'text', content: 'docs.matches.text1' },
      { type: 'image', src: 'assets/docs/matcheslist.png'},
      { type: 'tip', content: 'docs.matches.tip1' },
      { type: 'heading', content: 'docs.matches.heading1' },
      { type: 'text', content: 'docs.matches.text2' },
      { type: 'image', src: 'assets/docs/addmatch1.png'},
      { type: 'text', content: 'docs.matches.text3' },
      { type: 'image', src: 'assets/docs/addmatch2.png'},
      { type: 'text', content: 'docs.matches.text4' },
      { type: 'image', src: 'assets/docs/addmatch3.png'},
      { type: 'text', content: 'docs.matches.text5' },
      { type: 'image', src: 'assets/docs/addmatch4.png'},
      { type: 'text', content: 'docs.matches.text6' },
      { type: 'heading', content: 'docs.matches.heading2' },
      { type: 'text', content: 'docs.matches.text7' },
      { type: 'image', src: 'assets/docs/matchdetail1.png'},
      { type: 'image', src: 'assets/docs/matchdetail2.png'},
      { type: 'tip', content: 'docs.matches.tip2' },
      { type: 'heading', content: 'Editing or Deleting a Match' },
      { type: 'text', content: 'docs.matches.text8' },
      { type: 'heading', content: 'Starting a Match' },
      { type: 'text', content: 'docs.matches.text9' },
      { type: 'image', src: 'assets/docs/startmatch.png'},
      { type: 'tip', content: 'docs.matches.tip3' },
    ]
  },
  {
    id: 'running-match',
    title: 'docs.runningamatch.title',
    blocks: [
      { type: 'text', content: 'docs.runningamatch.text1' },
      { type: 'tip', content: 'docs.runningamatch.tip1' },
      { type: 'warning', content: 'docs.runningamatch.warning1'},
      { type: 'warning', content: 'docs.runningamatch.warning2'},
      { type: 'heading', content: 'docs.runningamatch.heading1' },
      { type: 'text', content: 'docs.runningamatch.text2' },
      { type: 'image', src: 'assets/docs/time.png'},
      { type: 'tip', content: 'docs.runningamatch.tip2' },
      { type: 'heading', content: 'docs.runningamatch.heading2' },
      { type: 'text', content: 'docs.runningamatch.text3' },
      { type: 'image', src: 'assets/docs/goals.png'},
      { type: 'heading', content: 'docs.runningamatch.heading3' },
      { type: 'text', content: 'docs.runningamatch.text4' },
      { type: 'image', src: 'assets/docs/cards.png'},
      { type: 'tip', content: 'docs.runningamatch.tip3' },
      { type: 'heading', content: 'docs.runningamatch.heading4' },
      { type: 'text', content: 'docs.runningamatch.text5' },
      { type: 'image', src: 'assets/docs/metrics.png'},
      { type: 'tip', content: 'docs.runningamatch.tip4' },
      { type: 'heading', content: 'docs.runningamatch.heading5' },
      { type: 'text', content: 'docs.runningamatch.text6' },
      { type: 'image', src: 'assets/docs/settings.png'},
      { type: 'heading', content: 'docs.runningamatch.heading6' },
      { type: 'text', content: 'docs.runningamatch.text7' },
      { type: 'warning', content: 'docs.runningamatch.warning3'},
      { type: 'heading', content: 'docs.runningamatch.heading7' },
      { type: 'text', content: 'docs.runningamatch.text8' },
      { type: 'image', src: 'assets/docs/extraviews.png'},
      { type: 'heading', content: 'docs.runningamatch.heading8'},
      { type: 'text', content: 'docs.runningamatch.text9' },
    ]
  },
  {
    id: 'shootouts',
    title: 'docs.shootouts.title',
    blocks: [
      { type: 'text', content: 'docs.shootouts.text1' },
      { type: 'heading', content: 'docs.shootouts.heading1' },
      { type: 'text', content: 'docs.shootouts.text2' },
      { type: 'image', src: 'assets/docs/shootouttime.png'},
      { type: 'heading', content: 'docs.shootouts.heading2' },
      { type: 'text', content: 'docs.shootouts.text3' },
      { type: 'image', src: 'assets/docs/shootoutgoals.png'},
      { type: 'tip', content: 'docs.shootouts.tip1' },
      { type: 'heading', content: 'docs.shootouts.heading3' },
      { type: 'text', content: 'docs.shootouts.text4' },
    ]
  },
  {
    id: 'Synchronisation',
    title: 'docs.synchronisation.title',
    blocks: [
      { type: 'text', content: 'docs.synchronisation.text1' },
      { type: 'warning', content: 'docs.synchronisation.warning1' },
      { type: 'warning', content: 'docs.synchronisation.warning2' },
      { type: 'heading', content: 'docs.synchronisation.heading1' },
      { type: 'text', content: 'docs.synchronisation.text2' },
      { type: 'image', src: 'assets/docs/hostmatch.png'},
      { type: 'warning', content: 'docs.synchronisation.warning3' },
      { type: 'heading', content: 'Joining a Match' },
      { type: 'text', content: 'To join a match, go to the matches list and press the menu button on the top right. Then click the "Join Match" option and enter the 4 letter key provided by the host aswell as your name to identify yourself to others. Once joined, you will be brought to the match views just like how you would normally when starting your own match.' },
      { type: 'image', src: 'assets/docs/joinmatch.png'},
      { type: 'warning', content: 'docs.synchronisation.warning4' },
      { type: 'heading', content: 'docs.synchronisation.heading2' },
      { type: 'text', content: 'docs.synchronisation.text3' },
      { type: 'image', src: 'assets/docs/synchronisation.png'},
      { type: 'tip', content: 'docs.synchronisation.tip1' },
      { type: 'heading', content: 'docs.synchronisation.heading3' },
      { type: 'text', content: 'docs.synchronisation.text4' },
      { type: 'warning', content: 'docs.synchronisation.warning5' },
    ]
  },
  {
    id: 'location',
    title: 'docs.location.title',
    blocks: [
      { type: 'text', content: 'docs.location.text1' },
      { type: 'warning', content: 'docs.location.warning1' },
      { type: 'image', src: 'assets/docs/location.png'},
      { type: 'heading', content: 'docs.location.heading1' },
      { type: 'text', content: 'docs.location.text2' },
      { type: 'tip', content: 'docs.location.tip1' },
      { type: 'heading', content: 'docs.location.heading2' },
      { type: 'text', content: 'docs.location.text3' },
      { type: 'image', src: 'assets/docs/heatmap.png'},
      { type: 'warning', content: 'docs.location.warning2' },
    ]
  },
  {
    id: 'settings',
    title: 'docs.settings.title',
    blocks: [
      { type: 'text', content: 'docs.settings.text1' },
      { type: 'heading', content: 'docs.settings.heading1' },
      { type: 'text', content: 'docs.settings.text2' },
      { type: 'tip', content: 'docs.settings.tip1' },
      { type: 'text', content: 'docs.settings.text3' },
      { type: 'heading', content: 'docs.settings.heading2' },
      { type: 'text', content: 'docs.settings.text4' },
      { type: 'heading', content: 'docs.settings.heading3' },
      { type: 'text', content: 'docs.settings.text5' },
      { type: 'tip', content: 'docs.settings.tip2' },
    ]
  },
  {
    id: 'action-button',
    title: 'docs.actionbutton.title',
    blocks: [
      { type: 'text', content: 'docs.actionbutton.text1' },
      { type: 'warning', content: 'docs.actionbutton.warning1' },
      { type: 'heading', content: 'docs.actionbutton.heading1' },
      { type: 'text', content: 'docs.actionbutton.text2' },
    ]
  }
];
